#!/usr/bin/env python3
"""
Format institutional_picks_daily_pct_change reports:
  - round to 2 decimals
  - transpose (symbols as rows, dates as columns)
  - strip 'NSE:' prefix from symbols
  - Excel-style green highlights:
      move > 3%  => light green fill
      move > 5%  => darker green fill
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill


def strip_exchange_prefix(sym: str) -> str:
    s = str(sym)
    if ":" in s:
        return s.split(":", 1)[1]
    return s


def main() -> None:
    parser = argparse.ArgumentParser(description="Format institutional picks daily % change report.")
    parser.add_argument(
        "--input-csv",
        default=str(Path("reports") / "institutional_picks_daily_pct_change_03apr2026_to_16apr2026.csv"),
        help="Input CSV generated by institutional_picks_daily_pct_change_kite.py",
    )
    parser.add_argument(
        "--out-xlsx",
        default=None,
        help="Output formatted XLSX path. Default: add '_formatted_transposed' suffix in reports/.",
    )
    parser.add_argument(
        "--out-csv",
        default=None,
        help="Optional output transposed/rounded CSV path.",
    )
    args = parser.parse_args()

    input_csv = Path(args.input_csv)
    if not input_csv.exists():
        raise SystemExit(f"Input not found: {input_csv}")

    out_xlsx = (
        Path(args.out_xlsx)
        if args.out_xlsx
        else input_csv.with_name(input_csv.stem + "_formatted_transposed.xlsx")
    )
    out_csv = (
        Path(args.out_csv)
        if args.out_csv
        else input_csv.with_name(input_csv.stem + "_formatted_transposed.csv")
    )

    df = pd.read_csv(input_csv)
    if "date" not in df.columns:
        raise SystemExit("CSV must have a 'date' column as the first column header.")

    # Round values (non-numeric columns are not expected here).
    value_cols = [c for c in df.columns if c != "date"]
    df[value_cols] = df[value_cols].apply(pd.to_numeric, errors="coerce")
    df[value_cols] = df[value_cols].round(2)

    # Transpose:
    #   input: index=date, columns=symbols
    #   output: index=symbols (rows), columns=date (dates)
    df = df.set_index("date")
    df.columns = [strip_exchange_prefix(c) for c in df.columns]
    df_t = df.transpose()

    # Save transposed CSV (simple numeric view).
    df_t.index.name = "Symbol"
    df_t.to_csv(out_csv, index=True)

    # Build formatted XLSX.
    wb = Workbook()
    ws = wb.active
    ws.title = "daily_pct_change"

    # Header row: dates
    dates = list(df_t.columns)
    ws.cell(row=1, column=1, value="Symbol")
    ws.cell(row=1, column=1).font = Font(bold=True)
    for j, d in enumerate(dates, start=2):
        ws.cell(row=1, column=j, value=str(d)).font = Font(bold=True)

    # Styles
    light_fill = PatternFill(start_color="FFE6F4EA", end_color="FFE6F4EA", fill_type="solid")
    dark_fill = PatternFill(start_color="FF2E7D32", end_color="FF2E7D32", fill_type="solid")
    normal_font = Font(color="FF000000")
    white_font = Font(color="FFFFFFFF")
    center = Alignment(horizontal="center", vertical="center")

    # Fill cells with conditional shading.
    for i, sym in enumerate(df_t.index, start=2):
        ws.cell(row=i, column=1, value=str(sym)).font = Font(bold=False)
        ws.cell(row=i, column=1).alignment = Alignment(horizontal="left")
        for j, d in enumerate(dates, start=2):
            val = df_t.loc[sym, d]
            cell = ws.cell(row=i, column=j, value=None if pd.isna(val) else float(val))
            cell.alignment = center
            cell.number_format = "0.00"

            if pd.notna(val):
                if float(val) > 5.0:
                    cell.fill = dark_fill
                    cell.font = white_font
                elif float(val) > 3.0:
                    cell.fill = light_fill
                    cell.font = normal_font
                else:
                    cell.fill = PatternFill()  # no fill
                    cell.font = normal_font

    # Column widths
    ws.column_dimensions["A"].width = 18
    for col_idx in range(2, 2 + len(dates)):
        ws.column_dimensions[ws.cell(row=1, column=col_idx).column_letter].width = 12

    # Freeze panes just below header row.
    ws.freeze_panes = "B2"

    # Write file
    wb.save(out_xlsx)
    print(f"CSV  -> {out_csv}")
    print(f"XLSX -> {out_xlsx}")


if __name__ == "__main__":
    main()

